import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TawkTo from "@/services/TawkTo";
import LogRocket from "@/services/LogRocket";
import Navbar from "@/components/Shared/Navbar";
import Footer from "@/components/Shared/Footer";
import GoogleAnalytics from "@/services/GoogleAnalytics";

export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900 text-black dark:text-white transition-colors duration-300`}
      >
        <Navbar />
        <TawkTo />
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID} />
        <LogRocket />
        {children}
        <Footer />
      </body>
    </html>
  );
}
